from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, Integer, Float

Base = declarative_base()


class Live(Base):
    __tablename__ = 'live'
    id = Column(String(255), nullable=False, default=None, primary_key=True)
    object_type = Column(String(255), nullable=False, default=None)
    source_type = Column(String(255), nullable=False, default=None)
    live_liked = Column(Integer, nullable=False, default=None)
    live_is_commercial = Column(Integer, nullable=False, default=None)
    live_seats_taken = Column(Integer, nullable=False, default=None)
    live_seats_max = Column(Integer, nullable=False, default=None)
    live_id = Column(String(255), nullable=False, default=None)
    live_in_promotion = Column(Integer, nullable=False, default=None)
    live_fee_original_price = Column(Integer, nullable=False, default=None)
    live_fee_amount = Column(Integer, nullable=False, default=None)
    live_fee_unit = Column(String(255), nullable=False, default=None)
    live_review_count = Column(Integer, nullable=False, default=None)
    live_review_status = Column(String(255), nullable=False, default=None)
    live_review_score = Column(Float(20, 5), nullable=False, default=None)
    live_review_has_reviewed = Column(Integer, nullable=False, default=None)
    live_review_previous_status = Column(String(255), nullable=False, default=None)
    live_review_previous_score = Column(Integer, nullable=False, default=None)
    live_cospeakers = Column(String(255), nullable=False, default=None)
    live_speaker_member_is_followed = Column(Integer, nullable=False, default=None)
    live_speaker_member_badge = Column(String(255), nullable=False, default=None)
    live_speaker_member_name = Column(String(255), nullable=False, default=None)
    live_speaker_member_url = Column(String(255), nullable=False, default=None)
    live_speaker_member_type = Column(String(255), nullable=False, default=None)
    live_speaker_member_user_type = Column(String(255), nullable=False, default=None)
    live_speaker_member_headline = Column(String(255), nullable=False, default=None)
    live_speaker_member_avatar_url = Column(String(255), nullable=False, default=None)
    live_speaker_member_is_following = Column(Integer, nullable=False, default=None)
    live_speaker_member_gender = Column(Integer, nullable=False, default=None)
    live_speaker_member_url_token = Column(String(255), nullable=False, default=None)
    live_speaker_member_id = Column(String(255), nullable=False, default=None)
    live_speaker_bio = Column(String(255), nullable=False, default=None)
    live_speaker_description = Column(String(3000), nullable=False, default=None)
    live_role = Column(String(255), nullable=False, default=None)
    live_subject = Column(String(255), nullable=False, default=None)
    live_type = Column(String(255), nullable=False, default=None)
    live_brand_label = Column(String(255), nullable=False, default=None)
    live_status = Column(String(255), nullable=False, default=None)
    live_ends_in = Column(Integer, nullable=False, default=None)
    live_is_audition_open = Column(Integer, nullable=False, default=None)
    live_speaker_message_count = Column(Integer, nullable=False, default=None)
    live_tags = Column(String(255), nullable=False, default=None)
    live_live_type = Column(String(255), nullable=False, default=None)
    live_liked_num = Column(Integer, nullable=False, default=None)
    live_artwork = Column(String(255), nullable=False, default=None)
    live_is_public = Column(Integer, nullable=False, default=None)
    live_ends_at = Column(Integer, nullable=False, default=None)
    live_has_audition = Column(Integer, nullable=False, default=None)
    live_is_brand = Column(Integer, nullable=False, default=None)
    live_starts_at = Column(Integer, nullable=False, default=None)
    action = Column(String(255), nullable=False, default=None)
    source_id = Column(Integer, nullable=False, default=None)

    def __repr__(self):
        return self.__dict__
